pipeline {
    agent any
    stages{
        stage("Clean UP")
        steps {
            deleteDir()
        }
        stage("Clone Repo")
        steps {
            sh "git clone https://github.com/VJCodeSlinger/Jenkins-CI-CD-Pipeline-Integration.git"
        }
        stage("Build"){
            steps {
                dir("Jenkins-CI-CD-Pipeline-Integration"){
                    sh "python setup.py clean --all"
                }
            }
        }
        stage("Test"){
            steps {
                dir("Jenkins-CI-CD-Pipeline-Integration"){
                    sh "pytest test"
                }                
            }
        }
    }
}